DROP DATABASE IF EXISTS BabyNames;

CREATE DATABASE BabyNames;

USE BabyNames;

CREATE TABLE name (
  id INT NOT NULL AUTO_INCREMENT,
  letter varchar(50) NOT NULL,
  girlNames varchar(50) NOT NULL,
  boyNames varchar(50) NOT NULL,
  PRIMARY KEY (ID)
);

/*  Execute this file from the command line by typing:
 *    mysql -u root < server/schema.sql
 *  to create the database and the tables.*/

INSERT INTO name (letter, girlNames, boyNames) VALUES ('a', "Alex", "Andrea")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('a', "Anthony", "Amber")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('a', "Angel", "Anglique")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('a', "Armando", "Aida")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('a', "Arios", "Angie")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('b', "Bernie", "Britney")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('b', "Bob", "Beyonce")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('b', "Borja", "Bency")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('b', "Barack", "Blue")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('c', "Cesar", "Cardi")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('c', "Charles", "Catherine")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('c', "Coby", "Cynthia")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('d', "Dominic", "Diana")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('d', "Dorian", "Dannielle")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('d', "Danttel", "Delilah")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('e', "Elias", "Evelyn")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('e', "Evan", "Elizabeth")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('e', "Edward", "Esther")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('e', "Eric", "Erin")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('f', "Francis", "Felicia")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('f', "Felix", "Fantasia")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('f', "Fess", "Fatima")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('g', "Gael", "Garima")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('g', "Gohan", "Gina")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('g', "Goku", "Gloria")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('h', "Haley", "Hommer")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('h', "Hillary", "Harrison")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('h', "Haveniqua", "Hector")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('i', "Ivan", "Irma")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('i', "Isaac", "Ivy")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('i', "Israel", "Isabelle")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('j', "Jason", "Jacqueline")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('j', "Jeremiah", "Julia")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('j', "Jorge", "Jazmin")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('j', "Jack", "Joy")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('k', "Kendrick", "Karla")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('k', "Keith", "Kate")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('k', "Ken", "Karen")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('l', "Louis", "Lala")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('l', "Lucas", "Len")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('l', "Lance", "Lucy")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('m', "Marco", "Macy")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('m', "Morris", "Marcela")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('m', "Michael", "Melanie")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('n', "Nolan", "Nadiah")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('n', "Nathaniel", "Norma")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('n', "Nick", "Norah")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('o', "Omar", "Olinka")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('o', "Oscar", "Oakley")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('o', "Orochi", "Olivia")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('p', "Peter", "Pamela")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('p', "Paul", "Patricia")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('p', "Paco", "Priscilla")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('q', "Quinton", "Queen")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('q', "Quincey", "Quelina")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('q', "Quin", "Quisha")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('r', "Ramon", "Rosey")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('r', "Raul", "Ruth")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('r', "Raymond", "Rita")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('s', "Simon", "Samantha")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('s', "Sebastian", "Serena")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('s', "Scott", "Solange")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('t', "Tyrone", "Tamarah")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('t', "Timothy", "Tiffany")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('t', "Thomas", "Taylor")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('u', "Uriel", "Ursula")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('u', "Ulises", "Urbi")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('u', "Urien", "Uri")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('v', "Victor", "Valerie")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('v', "Valentin", "Veronica")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('v', "Vincent", "Vanessa")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('w', "Warren", "Wendy")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('w', "Washington", "Whitney")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('w', "Wesley", "Wilma")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('x', "Xavier", "Xena")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('x', "Xenos", "Xandra")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('x', "Xander", "Ximena")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('y', "Yaakov", "Yvonne")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('y', "Yael", "Yazmin")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('y', "Yahir", "Young")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('z', "Zach", "Zabie")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('z', "Zackery", "Zada")
INSERT INTO name (letter, girlNames, boyNames) VALUES ('z', "Zane", "Zoraya")
